import AppKit
import CryptoKit
import Observation
import UserNotifications

@Observable
final class PasteboardService {
    private(set) var clipboardItems: [ClipboardItem] = []

    private static let maxImageBytes = 10 * 1024 * 1024
    private static let skippedTypes = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ].map { NSPasteboard.PasteboardType($0) }

    @ObservationIgnored private let settings: AppSettings
    @ObservationIgnored private let store: HistoryStore
    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private var changeCount: Int
    @ObservationIgnored private var timer: Timer?

    init(settings: AppSettings, store: HistoryStore, pasteboard: NSPasteboard = .general) {
        self.settings = settings
        self.store = store
        self.pasteboard = pasteboard
        changeCount = pasteboard.changeCount
        if settings.persistHistory {
            clipboardItems = store.load()
        }
        observeChanges({ settings.pollingInterval }) { [weak self] in self?.startTimer(interval: $0) }
        observeChanges({ settings.maxItems }) { [weak self] _ in self?.persistChanges() }
        observeChanges({ settings.persistHistory }) { [weak self] in self?.persistHistoryDidChange(enabled: $0) }
        observeChanges({ settings.showNotifications }) { if $0 { Self.requestNotificationAuthorization() } }
    }

    deinit {
        timer?.invalidate()
    }

    func copyToClipboard(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.content, forType: .string)
        case .image:
            if let image = item.image {
                pasteboard.writeObjects([image])
            }
        case .file:
            pasteboard.writeObjects(item.fileURLs as [NSURL])
        }
        changeCount = pasteboard.changeCount
    }

    func removeItem(_ item: ClipboardItem) {
        clipboardItems.removeAll { $0.id == item.id }
        persistChanges()
    }

    func clearAll() {
        clipboardItems.removeAll()
        persistChanges()
    }

    private func startTimer(interval: TimeInterval) {
        timer?.invalidate()
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.checkForChanges()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func checkForChanges() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        let types = pasteboard.types ?? []
        guard !types.contains(where: Self.skippedTypes.contains) else { return }
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let source, settings.excludedBundleIdentifiers.contains(source) { return }
        guard let item = readItem(source: source) else { return }
        record(item)
    }

    private func readItem(source: String?) -> ClipboardItem? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let names = urls.map(\.lastPathComponent).joined(separator: ", ")
            return ClipboardItem(kind: .file, content: names, fileURLs: urls, sourceBundleIdentifier: source)
        }
        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipboardItem(kind: .text, content: text, sourceBundleIdentifier: source)
        }
        guard settings.captureImages,
              let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
              data.count <= Self.maxImageBytes,
              let image = NSImage(data: data) else { return nil }
        let digest = Data(SHA256.hash(data: data)).base64EncodedString()
        let description = "Image \(Int(image.size.width))×\(Int(image.size.height))"
        return ClipboardItem(kind: .image, content: description, image: image, imageDigest: digest, sourceBundleIdentifier: source)
    }

    private func record(_ item: ClipboardItem) {
        if let index = clipboardItems.firstIndex(where: { $0.hasSameContent(as: item) }) {
            let existing = clipboardItems.remove(at: index)
            clipboardItems.insert(item.withID(existing.id), at: 0)
        } else {
            clipboardItems.insert(item, at: 0)
            if settings.showNotifications {
                notify(about: item)
            }
        }
        persistChanges()
    }

    private func persistChanges() {
        if clipboardItems.count > settings.maxItems {
            clipboardItems.removeLast(clipboardItems.count - settings.maxItems)
        }
        if settings.persistHistory {
            store.save(clipboardItems)
        }
    }

    private func persistHistoryDidChange(enabled: Bool) {
        if enabled {
            store.save(clipboardItems)
        } else {
            store.deleteAll()
        }
    }

    private func notify(about item: ClipboardItem) {
        let content = UNMutableNotificationContent()
        content.title = "Copied"
        content.body = String(item.content.prefix(100))
        let request = UNNotificationRequest(identifier: item.id.uuidString, content: content, trigger: nil)
        UNUserNotificationCenter.current().add(request)
    }

    private static func requestNotificationAuthorization() {
        UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound]) { _, _ in }
    }
}
